### PR TITLE
Fix open/close logic for SR-ZG9080A

### LINKED ISSUE #2910: New device support request - SR-ZG9080A
SR-ZG9080A is a window cover control by Sunricher. 

#2432 Added support for this device, but with the incorrect open/close logic:
Current deCONZ API integration set `state.bri` 0 when fully closed, AND `state.bri` is 254 when fully open.

image
image
image

Level Cluster attributes when fully closed:
image
Level Cluster attributes when fully open:
image

### PR DESCRIPTION
**Pull request by cgiraldo**
Fix #2910

### CODE REVIEW

File: window_covering.cpp [hunk 1]
```diff
@@ -164,7 +164,9 @@ void DeRestPluginPrivate::handleWindowCoveringClusterIndication(const deCONZ::Ap
 
                 quint8 lift = attrValue;
                 // Reverse value for Xiaomi curtain and Legrand switch
-                if (lightNode->modelId().startsWith(QLatin1String("lumi.curtain")) || (lightNode->modelId() == QLatin1String("Shutter switch with neutral")))
+                if (lightNode->modelId().startsWith(QLatin1String("lumi.curtain")) || 
+                (lightNode->modelId() == QLatin1String("Motor Controller")) ||
+                (lightNode->modelId() == QLatin1String("Shutter switch with neutral")))
```
Comment (SwoopX) [inline window_covering.cpp:169]: Please correct the indent here.

File: rest_lights.cpp [hunk 2]
```diff
@@ -1601,6 +1601,10 @@ int DeRestPluginPrivate::setWindowCoveringState(const ApiRequest &req, ApiRespon
             // Legrand invert bri and don't support other value than 0
             targetLiftZigBee = targetLift == 0 ? 100 : 0;
         }
+        else if (taskRef.lightNode->modelId() == QLatin1String("Motor Controller"))
+        {
+            targetLiftZigBee = 100 - targetLift;
+        }
```
Comment (SwoopX) [inline rest_lights.cpp:1607]: Please remove the 2 `else if` and move the modelId's to the if-clause with ORs, as you did in `windows_covering.cpp`.

**Comment by cgiraldo** [comment]
I have fix the comments
